// Code generated by MockGen. DO NOT EDIT.
// Source: authentication_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuthenticationRepository is a mock of IAuthenticationRepository interface.
type MockIAuthenticationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthenticationRepositoryMockRecorder
}

// MockIAuthenticationRepositoryMockRecorder is the mock recorder for MockIAuthenticationRepository.
type MockIAuthenticationRepositoryMockRecorder struct {
	mock *MockIAuthenticationRepository
}

// NewMockIAuthenticationRepository creates a new mock instance.
func NewMockIAuthenticationRepository(ctrl *gomock.Controller) *MockIAuthenticationRepository {
	mock := &MockIAuthenticationRepository{ctrl: ctrl}
	mock.recorder = &MockIAuthenticationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthenticationRepository) EXPECT() *MockIAuthenticationRepositoryMockRecorder {
	return m.recorder
}

// RefreshSessionExpiration mocks base method.
func (m *MockIAuthenticationRepository) RefreshSessionExpiration(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSessionExpiration", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshSessionExpiration indicates an expected call of RefreshSessionExpiration.
func (mr *MockIAuthenticationRepositoryMockRecorder) RefreshSessionExpiration(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSessionExpiration", reflect.TypeOf((*MockIAuthenticationRepository)(nil).RefreshSessionExpiration), key)
}

// SignIn mocks base method.
func (m *MockIAuthenticationRepository) SignIn(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignIn indicates an expected call of SignIn.
func (mr *MockIAuthenticationRepositoryMockRecorder) SignIn(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockIAuthenticationRepository)(nil).SignIn), key, value)
}

// SignOut mocks base method.
func (m *MockIAuthenticationRepository) SignOut(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignOut", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignOut indicates an expected call of SignOut.
func (mr *MockIAuthenticationRepositoryMockRecorder) SignOut(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOut", reflect.TypeOf((*MockIAuthenticationRepository)(nil).SignOut), key)
}
