// Code generated by MockGen. DO NOT EDIT.
// Source: telemetry_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	entity "github.com/To-ge/gr_backend_go/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockITelemetryRepository is a mock of ITelemetryRepository interface.
type MockITelemetryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITelemetryRepositoryMockRecorder
}

// MockITelemetryRepositoryMockRecorder is the mock recorder for MockITelemetryRepository.
type MockITelemetryRepositoryMockRecorder struct {
	mock *MockITelemetryRepository
}

// NewMockITelemetryRepository creates a new mock instance.
func NewMockITelemetryRepository(ctrl *gomock.Controller) *MockITelemetryRepository {
	mock := &MockITelemetryRepository{ctrl: ctrl}
	mock.recorder = &MockITelemetryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITelemetryRepository) EXPECT() *MockITelemetryRepositoryMockRecorder {
	return m.recorder
}

// CreateLocation mocks base method.
func (m *MockITelemetryRepository) CreateLocation(arg0 entity.Location) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocation", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLocation indicates an expected call of CreateLocation.
func (mr *MockITelemetryRepositoryMockRecorder) CreateLocation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocation", reflect.TypeOf((*MockITelemetryRepository)(nil).CreateLocation), arg0)
}
