// Code generated by MockGen. DO NOT EDIT.
// Source: location_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	entity "github.com/To-ge/gr_backend_go/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockILocationRepository is a mock of ILocationRepository interface.
type MockILocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILocationRepositoryMockRecorder
}

// MockILocationRepositoryMockRecorder is the mock recorder for MockILocationRepository.
type MockILocationRepositoryMockRecorder struct {
	mock *MockILocationRepository
}

// NewMockILocationRepository creates a new mock instance.
func NewMockILocationRepository(ctrl *gomock.Controller) *MockILocationRepository {
	mock := &MockILocationRepository{ctrl: ctrl}
	mock.recorder = &MockILocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILocationRepository) EXPECT() *MockILocationRepositoryMockRecorder {
	return m.recorder
}

// StreamArchiveLocation mocks base method.
func (m *MockILocationRepository) StreamArchiveLocation(arg0 entity.TimeSpan) (*entity.LocationChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamArchiveLocation", arg0)
	ret0, _ := ret[0].(*entity.LocationChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamArchiveLocation indicates an expected call of StreamArchiveLocation.
func (mr *MockILocationRepositoryMockRecorder) StreamArchiveLocation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamArchiveLocation", reflect.TypeOf((*MockILocationRepository)(nil).StreamArchiveLocation), arg0)
}
