// Code generated by MockGen. DO NOT EDIT.
// Source: telemetry_log_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	entity "github.com/To-ge/gr_backend_go/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockITelemetryLogRepository is a mock of ITelemetryLogRepository interface.
type MockITelemetryLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITelemetryLogRepositoryMockRecorder
}

// MockITelemetryLogRepositoryMockRecorder is the mock recorder for MockITelemetryLogRepository.
type MockITelemetryLogRepositoryMockRecorder struct {
	mock *MockITelemetryLogRepository
}

// NewMockITelemetryLogRepository creates a new mock instance.
func NewMockITelemetryLogRepository(ctrl *gomock.Controller) *MockITelemetryLogRepository {
	mock := &MockITelemetryLogRepository{ctrl: ctrl}
	mock.recorder = &MockITelemetryLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITelemetryLogRepository) EXPECT() *MockITelemetryLogRepositoryMockRecorder {
	return m.recorder
}

// CreateTelemetryLog mocks base method.
func (m *MockITelemetryLogRepository) CreateTelemetryLog(arg0 entity.TelemetryLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTelemetryLog", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTelemetryLog indicates an expected call of CreateTelemetryLog.
func (mr *MockITelemetryLogRepositoryMockRecorder) CreateTelemetryLog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTelemetryLog", reflect.TypeOf((*MockITelemetryLogRepository)(nil).CreateTelemetryLog), arg0)
}

// GetPublicTelemetryLogs mocks base method.
func (m *MockITelemetryLogRepository) GetPublicTelemetryLogs() ([]entity.TelemetryLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicTelemetryLogs")
	ret0, _ := ret[0].([]entity.TelemetryLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicTelemetryLogs indicates an expected call of GetPublicTelemetryLogs.
func (mr *MockITelemetryLogRepositoryMockRecorder) GetPublicTelemetryLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicTelemetryLogs", reflect.TypeOf((*MockITelemetryLogRepository)(nil).GetPublicTelemetryLogs))
}

// GetTelemetryLogs mocks base method.
func (m *MockITelemetryLogRepository) GetTelemetryLogs() ([]entity.TelemetryLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelemetryLogs")
	ret0, _ := ret[0].([]entity.TelemetryLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelemetryLogs indicates an expected call of GetTelemetryLogs.
func (mr *MockITelemetryLogRepositoryMockRecorder) GetTelemetryLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelemetryLogs", reflect.TypeOf((*MockITelemetryLogRepository)(nil).GetTelemetryLogs))
}

// ToggleTelemetryLogVisibility mocks base method.
func (m *MockITelemetryLogRepository) ToggleTelemetryLogVisibility(id uint, visible bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleTelemetryLogVisibility", id, visible)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleTelemetryLogVisibility indicates an expected call of ToggleTelemetryLogVisibility.
func (mr *MockITelemetryLogRepositoryMockRecorder) ToggleTelemetryLogVisibility(id, visible interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleTelemetryLogVisibility", reflect.TypeOf((*MockITelemetryLogRepository)(nil).ToggleTelemetryLogVisibility), id, visible)
}
